# actionsタブに表示されるワークフロー名（任意）
# 設定しない場合はファイル名となる
name: Sample Workflow

# このワークフローが実行されるイベント設定
on:
 # mainブランチへのpushで発火
 # push以外でもpull_request、merge、issueの種別など設定可能
 push:
   branches:
    # ブランチ名（任意） [main, develop]のように配列指定も可
     - main
 # actionsタブからの手動実行を可能にする
 workflow_dispatch:

# 実行するジョブの定義
jobs:
 # ジョブ名（任意）
 hello_world_job:
   # 実行するOSの種類
   runs-on: ubuntu-latest
   # 実行するステップを一覧を定義するブロック
   steps:
     # ステップ名（任意）
     - name: Checkout code
       # 使用するライブラリなど
       uses: actions/checkout@v3
     - name: Print Hellow World And My Name!
       run: echo "Hello World! MyName is ${{ github.actor }}"